package compass;

import tech.tablesaw.api.*;
import java.util.*;
import org.junit.jupiter.api.*;
import java.util.stream.Stream;

import javax.annotation.concurrent.GuardedBy;

import java.util.stream.Collector;
import java.util.concurrent.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.*;

public class ConcurrencyTest {

    void showTestName(TestInfo testInfo){
        String methodName = testInfo.getTestMethod().orElseThrow().getName();
        System.out.println("\n================================");
        System.out.println(methodName);
        System.out.println("================================");
    }

    @BeforeEach
    void setup(TestInfo testInfo){
        showTestName(testInfo);
        //TODO: directly manipulate the update() function to populate
        // insertion and deletions to test.
        // load data from the file, calculate the ground truth and compare
        // with the results generated by PASS.
    }

    @AfterEach
    void clean(){
    }

}